/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apresentacao;

import Dados.vquartos;
import Logica.fquartos;
import Logica.fstatus_quarto;
import java.awt.Color;
import java.awt.Component;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author filin
 */
public class frm_status_quarto extends javax.swing.JInternalFrame {

    ResultSet rs;

    /**
     * Creates new form frm_mostrarquartos
     */
    public frm_status_quarto() {
        initComponents();
        ListarQuarto();
        TB_lista.setDefaultRenderer(Object.class, new pintar_linha());
    }
    
     void ocultar_coluna(){
        TB_lista.getColumnModel().getColumn(0).setMaxWidth(0);
        TB_lista.getColumnModel().getColumn(0).setMinWidth(0);
        TB_lista.getColumnModel().getColumn(0).setPreferredWidth(0);
        
        TB_lista.getColumnModel().getColumn(3).setMaxWidth(0);
        TB_lista.getColumnModel().getColumn(3).setMinWidth(0);
        TB_lista.getColumnModel().getColumn(3).setPreferredWidth(0);
        
        TB_lista.getColumnModel().getColumn(4).setMaxWidth(0);
        TB_lista.getColumnModel().getColumn(4).setMinWidth(0);
        TB_lista.getColumnModel().getColumn(4).setPreferredWidth(0);
    }

    private void ListarQuarto() {

        try {
            fstatus_quarto objquarto = new fstatus_quarto();
            DefaultTableModel modelo = (DefaultTableModel) TB_lista.getModel();

            modelo.setNumRows(0);
            ArrayList<vquartos> lista = objquarto.PesquisarQuartos();

            for (int num = 0; num < lista.size(); num++) {
                modelo.addRow(new Object[]{
                    lista.get(num).getIdquartos(),
                    lista.get(num).getNumero(),
                    lista.get(num).getAndar(),
                    lista.get(num).getDescricao(),
                    lista.get(num).getCaracteristicas(),
                    lista.get(num).getValordiaria(),
                    lista.get(num).getEstado(),
                    lista.get(num).getTipoquarto()

                });

            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Listar quartos: " + erro);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TB_lista = new javax.swing.JTable();
        btn_sair = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoscrolls(true);
        setDoubleBuffered(true);
        setFocusTraversalPolicyProvider(true);
        setInheritsPopupMenu(true);
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setAutoscrolls(true);
        jPanel2.setFocusCycleRoot(true);
        jPanel2.setFocusTraversalPolicyProvider(true);
        jPanel2.setInheritsPopupMenu(true);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Quartos Disponíveis");

        TB_lista.setAutoCreateRowSorter(true);
        TB_lista.setBackground(new java.awt.Color(204, 204, 204));
        TB_lista.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TB_lista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Número", "Andar", "Descrição", "Características", "Preço", "Estado", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TB_lista.setCellSelectionEnabled(true);
        TB_lista.setDoubleBuffered(true);
        TB_lista.setDragEnabled(true);
        TB_lista.setEditingColumn(0);
        TB_lista.setEditingRow(0);
        TB_lista.setFillsViewportHeight(true);
        TB_lista.setFocusCycleRoot(true);
        TB_lista.setFocusTraversalPolicyProvider(true);
        TB_lista.setInheritsPopupMenu(true);
        TB_lista.setRowHeight(23);
        TB_lista.setRowMargin(2);
        TB_lista.setRowSorter(null);
        TB_lista.setSurrendersFocusOnKeystroke(true);
        TB_lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TB_listaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TB_listaMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(TB_lista);

        btn_sair.setBackground(new java.awt.Color(0, 0, 255));
        btn_sair.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_sair.setText("Sair");
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_sair)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TB_listaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TB_listaMouseClicked


    }//GEN-LAST:event_TB_listaMouseClicked

    private void TB_listaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TB_listaMousePressed


    }//GEN-LAST:event_TB_listaMousePressed

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_sairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_status_quarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_status_quarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_status_quarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_status_quarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_status_quarto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TB_lista;
    private javax.swing.JButton btn_sair;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables

    public class pintar_linha extends DefaultTableCellRenderer {

        public pintar_linha() {
        }

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            JLabel label = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column); //To change body of generated methods, choose Tools | Templates.

            Color backgroud = Color.GREEN;

            Object objeto = TB_lista.getValueAt(row, 6);
            ocultar_coluna();

            try {
                String status = objeto.toString();
                if (status.equals("Ocupado")){
                    backgroud = Color.ORANGE;
                }else if (status.equals("Manutenção")){
                    backgroud = Color.RED;
                }else if(status.equals("Limpar")){
                    backgroud = Color.PINK;
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

            label.setBackground(backgroud);

            return label;

        }

    }
}
